# Version 1.0
FROM ubuntu:16.04

LABEL maintainer = "JavaPhotinia"

RUN apt-get update && apt install software-properties-common -y && add-apt-repository ppa:openjdk-r/ppa \ 
&& apt-get update && apt-get install vim -y && apt-get install wget -y 

RUN apt-get install unzip -y && apt-get install openjdk-8-jdk -y \
&& apt-get install -y \
  bison \
  build-essential \
  clang \
  cmake \
  doxygen \
  flex \
  g++ \
  git \
  libffi-dev \
  libncurses5-dev \
  libsqlite3-dev \
  make \
  mcpp \
  python \
  sqlite \
  zlib1g-dev 

RUN wget https://services.gradle.org/distributions/gradle-6.4-bin.zip \
&& unzip -d /usr/local/ gradle-6.4-bin.zip \
&& wget https://github.com/souffle-lang/souffle/releases/download/1.5.1/souffle_1.5.1-1_amd64.deb \
&& dpkg -i souffle_1.5.1-1_amd64.deb \
&& git clone https://bitbucket.org/yanniss/doop-benchmarks.git \
&& git clone https://github.com/JavaPhotinia/DOOP_Photinia.git \
&& git clone https://github.com/JavaPhotinia/Benchmarks.git

RUN mv /Benchmarks/ /root &&  mv /doop-benchmarks/ /root \
&& mv /DOOP_Photinia/* /root/ \
&& rm -rf doop.tar.gz && rm -rf gradle-6.4-bin.zip && rm -rf souffle_1.5.1-1_amd64.deb 

RUN find . -name "*DS_Store" | xargs rm -r

ENV GRADLE_HOME=/usr/local/gradle-6.4 PATH="/usr/local/gradle-6.4/bin:${PATH}" DOOP_HOME=/root/newdoop DOOP_OUT=/data/doop/out \
DOOP_CACHE=/data/doop/cache DOOP_TMP=/data/doop/tmp DOOP_LOG=/data/doop/log JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8 \
DOOP_PLATFORMS_LIB=/root/doop-benchmarks


