package utils;

public class StringConstantUtil {
    public static final String OBJECT_CLASS = "java.lang.Object";
    public static final String FILTER_REGISTRATION_CLASS = "org.springframework.boot.web.servlet.FilterRegistrationBean";
    public static final String INTERCEPTOR_REGISTRY_CLASS = "org.springframework.web.servlet.config.annotation.InterceptorRegistry";
    public static final String INTERCEPTOR_REGISTRATION_CLASS = "org.springframework.web.servlet.config.annotation.InterceptorRegistration";
    public static final String ANNOTATION_TYPE_RESTCONTROLLER = "Lorg/springframework/web/bind/annotation/RestController;";
    public static final String ANNOTATION_TYPE_CONTROLLER = "Lorg/springframework/web/bind/annotation/Controller;";
    public static final String ANNOTATION_TYPE_SCONTROLLER = "Lorg/springframework/stereotype/Controller;";
    public static final String ANNOTATION_TYPE_CONFIGURATION = "Lorg/springframework/context/annotation/Configuration;";
    public static final String ANNOTATION_TYPE_CONDITIONAL = "Lorg/springframework/context/annotation/Conditional;";
    public static final String ANNOTATION_TYPE_CONDITIONAL_ON_WEN = "Lorg/springframework/boot/autoconfigure/condition/ConditionalOnWebApplication;";
    public static final String ANNOTATION_TYPE_CONDITIONAL_ON_CLASS = "Lorg/springframework/boot/autoconfigure/condition/ConditionalOnClass;";
    public static final String ANNOTATION_TYPE_CONDITIONAL_ON_BEAN = "Lorg/springframework/boot/autoconfigure/condition/ConditionalOnBean;";
    public static final String ANNOTATION_TYPE_CONDITIONAL_ON_MISSING_BEAN = "Lorg/springframework/boot/autoconfigure/condition/ConditionalOnMissingBean;";
    public static final String ANNOTATION_TYPE_CONDITIONAL_ON_PROPERTY = "Lorg/springframework/boot/autoconfigure/condition/ConditionalOnProperty;";
    public static final String ANNOTATION_TYPE_IMPORT = "Lorg/springframework/context/annotation/Import;";
    public static final String ANNOTATION_TYPE_MAPPER = "Lorg/apache/ibatis/annotations/Mapper;";
    public static final String ANNOTATION_TYPE_SQLRESOURCE = "Lorg/beetl/sql/core/annotatoin/SqlResource;";
    public static final String ANNOTATION_TYPE_COMPONENT = "Lorg/springframework/stereotype/Component;";
    public static final String ANNOTATION_TYPE_REPOSITORY = "Lorg/springframework/stereotype/Repository;";
    public static final String ANNOTATION_TYPE_SERVICE = "Lorg/springframework/stereotype/Service;";
    public static final String ANNOTATION_TYPE_SCOPE = "Lorg/springframework/context/annotation/Scope;";
    public static final String ANNOTATION_TYPE_MAPPERSCAN = "Lorg/mybatis/spring/annotation/MapperScan;";
    public static final String ANNOTATION_TYPE_REQUESTMAPPING = "Lorg/springframework/web/bind/annotation/RequestMapping;";
    public static final String ANNOTATION_TYPE_POSTMAPPING = "Lorg/springframework/web/bind/annotation/PostMapping;";
    public static final String ANNOTATION_TYPE_GETMAPPING = "Lorg/springframework/web/bind/annotation/GetMapping;";
    public static final String ANNOTATION_TYPE_PATCHMAPPING = "Lorg/springframework/web/bind/annotation/PatchMapping;";
    public static final String ANNOTATION_TYPE_DELETEMAPPING = "Lorg/springframework/web/bind/annotation/DeleteMapping;";
    public static final String ANNOTATION_TYPE_PUTMAPPING = "Lorg/springframework/web/bind/annotation/PutMapping;";
    public static final String ANNOTATION_TYPE_ASPECT = "Lorg/aspectj/lang/annotation/Aspect;";
    public static final String ANNOTATION_TYPE_DOCUMENTED = "Ljava/lang/annotation/Documented;";
    public static final String ANNOTATION_TYPE_RETENTION = "Ljava/lang/annotation/Retention;";
    public static final String ANNOTATION_TYPE_TARGET = "Ljava/lang/annotation/Target;";
    public static final String AOP_PROCEED_METHOD_SIG = "<org.aspectj.lang.ProceedingJoinPoint: java.lang.Object proceed()>";
    public static final String AOP_PROCEED_METHOD_WITH_PAR_SIG = "<org.aspectj.lang.ProceedingJoinPoint: java.lang.Object proceed(java.lang.Object[])>";
    public static final String ANNOTATION_SPRING_BOOT = "Lorg/springframework/boot/autoconfigure/SpringBootApplication;";
    public static final String ANNOTATION_TYPE_MYBATIS_UPDATE = "Lorg/apache/ibatis/annotations/Update;";
    public static final String ANNOTATION_TYPE_MYBATIS_DELETE = "Lorg/apache/ibatis/annotations/Delete;";
    public static final String ANNOTATION_TYPE_MYBATIS_SELECT = "Lorg/apache/ibatis/annotations/Select;";
    public static final String ANNOTATION_TYPE_MYBATIS_INSERT = "Lorg/apache/ibatis/annotations/Insert;";
    public static final String ANNOTATION_TYPE_MYBATIS_INSERT_PROVIDER = "Lorg/apache/ibatis/annotations/InsertProvider;";
    public static final String ANNOTATION_TYPE_MYBATIS_SELECT_PROVIDER = "Lorg/apache/ibatis/annotations/SelectProvider;";
    public static final String ANNOTATION_TYPE_MYBATIS_DELETE_PROVIDER = "Lorg/apache/ibatis/annotations/DeleteProvider;";
    public static final String ANNOTATION_TYPE_MYBATIS_UPDATE_PROVIDER = "Lorg/apache/ibatis/annotations/UpdateProvider;";
    public static final String ANNOTATION_TYPE_JPA_QUERY = "Lorg/springframework/data/jpa/repository/Query;";
}
